/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grupob;

import controlador.Manager;
import java.util.ArrayList;
import javax.swing.JFrame;
import model.Distrito;
import model.Institucion;
import model.Local;
import model.Region;
import model.TipoProcesoVotacion;

/**
 *
 * @author USUARIO
 */
public class BusquedaPartidos extends javax.swing.JPanel {
    private static FramePrincipal padre;

    /**
     * Creates new form BusquedaPartidos
     */
    public BusquedaPartidos(FramePrincipal parent) {
        padre = parent;
        initComponents();
        busq_selecc_lugar.setVisible(false);
        busq_lugar.setVisible(false);
        busq_tipo.removeAllItems();
        ArrayList<TipoProcesoVotacion> procs = Manager.queryAllTipoProceso();
        busq_tipo.addItem("Todos");
        for(int i=0;i<procs.size();i++)
            busq_tipo.addItem(procs.get(i).getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        busq_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        busq_tipo = new javax.swing.JComboBox<>();
        boton_buscar = new javax.swing.JButton();
        boton_limpiar = new javax.swing.JButton();
        busq_selecc_lugar = new javax.swing.JLabel();
        busq_lugar = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Nombre del Partido:");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Tipo  de Proceso:");

        busq_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Nacional", "Distrital", "Regional", "Local", "Instituciones" }));
        busq_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busq_tipoActionPerformed(evt);
            }
        });

        boton_buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_buscar.setText("Buscar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });

        boton_limpiar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_limpiar.setText("Limpiar");
        boton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiarActionPerformed(evt);
            }
        });

        busq_selecc_lugar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        busq_selecc_lugar.setText("Seleccione:");

        busq_lugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Villa Maria del Triunfo", "Nuevo Chimbote" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(boton_limpiar)
                                .addGap(133, 133, 133)
                                .addComponent(boton_buscar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(busq_selecc_lugar)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(busq_nombre)
                                    .addComponent(busq_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(busq_lugar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(busq_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(busq_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busq_selecc_lugar)
                    .addComponent(busq_lugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_buscar)
                    .addComponent(boton_limpiar))
                .addGap(37, 37, 37))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 450, 250));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Búsqueda de Partido");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 330, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed

        String nombre = busq_nombre.getText();
        int indiceTipo = busq_tipo.getSelectedIndex();
        int indiceLugar = -1;
        if(busq_lugar.isVisible()){
            indiceLugar = busq_lugar.getSelectedIndex();
        }
        padre.mostrarResultadoBusqueda(nombre, indiceTipo, indiceLugar);
    }//GEN-LAST:event_boton_buscarActionPerformed

    private void busq_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busq_tipoActionPerformed
        // TODO add your handling code here:
        if(busq_tipo.getSelectedIndex()>1){
            busq_lugar.setVisible(true);
            busq_selecc_lugar.setVisible(true);
            int indice = busq_tipo.getSelectedIndex();
            busq_lugar.removeAllItems();
            busq_lugar.addItem("Todos");
            if(indice == 2){
                ArrayList<Region> regiones = Manager.queryAllRegion();
                for(int i = 0; i<regiones.size(); i++){
                    busq_lugar.addItem(regiones.get(i).getNombre());
                    //System.out.println("" + regiones.get(i).getNombre());
                }
            }
            if(indice == 3){
                ArrayList<Distrito> distritos = Manager.queryAllDistrito();
                for(int i=0; i<distritos.size();i++)
                    busq_lugar.addItem(distritos.get(i).getNombre());
            }
            if(indice == 4){
                
               ArrayList<Local> locales = Manager.queryAllLocales();
               for(int i = 0; i < locales.size() ; i++)
                   busq_lugar.addItem(locales.get(i).getNombre());
            }
            if(indice == 5){
                ArrayList<Institucion> locales = Manager.queryAllInstitucion();
                for(int i=0; i<locales.size();i++)
                    busq_lugar.addItem(locales.get(i).getNombre());
            }
        }
        else{
            busq_lugar.setVisible(false);
            busq_selecc_lugar.setVisible(false);
        }
    }//GEN-LAST:event_busq_tipoActionPerformed

    private void boton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_limpiarActionPerformed
        // TODO add your handling code here:
        busq_nombre.setText("");
        busq_tipo.setSelectedIndex(0);
        busq_lugar.setVisible(false);
        busq_selecc_lugar.setVisible(false);
    }//GEN-LAST:event_boton_limpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_buscar;
    private javax.swing.JButton boton_limpiar;
    private javax.swing.JComboBox<String> busq_lugar;
    private javax.swing.JTextField busq_nombre;
    private javax.swing.JLabel busq_selecc_lugar;
    private javax.swing.JComboBox<String> busq_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
