/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grupob;

import controlador.Manager;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import model.PartidoPolitico;
import model.Region;

/**
 *
 * @author USUARIO
 */
public class DetallePartido extends javax.swing.JPanel {

    /**
     * Creates new form DetallePartido
     */
    public static FramePrincipal padre;
    public static PartidoPolitico partidoPolitico;
    
    public DetallePartido(FramePrincipal parent) {
        padre = parent;
        initComponents();
        pestInstitucion.setVisible(false);
        pestDistrital.setVisible(false);
        pestNacional.setVisible(false);
        pestRegional.setVisible(false);
        pestLocal.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        pestNacional = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        estado1 = new javax.swing.JTextField();
        validarNuevos = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dni_rep1 = new javax.swing.JTextField();
        nombre_rep1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        correo1 = new javax.swing.JTextField();
        fechaReg1 = new com.toedter.calendar.JDateChooser();
        pestRegional = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_region = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        dni_rep2 = new javax.swing.JTextField();
        nombre_rep2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechaReg2 = new com.toedter.calendar.JDateChooser();
        correo2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pestDistrital = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        dni_rep3 = new javax.swing.JTextField();
        nombre_rep3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fechaReg3 = new com.toedter.calendar.JDateChooser();
        correo3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        pestLocal = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        dni_rep4 = new javax.swing.JTextField();
        nombre_rep4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        fechaReg4 = new com.toedter.calendar.JDateChooser();
        correo4 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        pestInstitucion = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        dni_rep5 = new javax.swing.JTextField();
        nombre_rep5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        fechaReg5 = new com.toedter.calendar.JDateChooser();
        correo5 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adherentesRevision = new javax.swing.JButton();
        nombre_partido = new javax.swing.JTextField();

        pestNacional.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Estado Actual:");
        pestNacional.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 93, 20));
        pestNacional.add(estado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 134, -1));

        validarNuevos.setText("Validar nuevos Adherentes");
        validarNuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarNuevosActionPerformed(evt);
            }
        });
        pestNacional.add(validarNuevos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 245, -1));

        jButton21.setText("Eliminar");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        pestNacional.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jLabel8.setText("Cantidad de Adherentes faltantes: ");
        pestNacional.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));
        pestNacional.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 50, -1));

        jLabel9.setText("Dni del Representante:");
        pestNacional.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 130, -1));

        dni_rep1.setEditable(false);
        pestNacional.add(dni_rep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 160, -1));

        nombre_rep1.setEditable(false);
        pestNacional.add(nombre_rep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 160, -1));

        jLabel10.setText("Nombre del Representante:");
        pestNacional.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, -1));

        jLabel1.setText("Correo:");
        pestNacional.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel2.setText("Fecha de Registro:");
        pestNacional.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        correo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correo1ActionPerformed(evt);
            }
        });
        pestNacional.add(correo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 160, -1));
        pestNacional.add(fechaReg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 120, 100, -1));

        jTabbedPane3.addTab("Nacional", pestNacional);

        tabla_region.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Region", "Estado Activo", "Cant. Adhs Faltantes", "Validar Nuevos", "Eliminar"
            }
        ));
        jScrollPane2.setViewportView(tabla_region);

        jLabel11.setText("Nombre del Representante:");

        dni_rep2.setEditable(false);

        nombre_rep2.setEditable(false);

        jLabel12.setText("Dni del Representante:");

        jLabel3.setText("Fecha de Registro:");

        correo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correo2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Correo:");

        javax.swing.GroupLayout pestRegionalLayout = new javax.swing.GroupLayout(pestRegional);
        pestRegional.setLayout(pestRegionalLayout);
        pestRegionalLayout.setHorizontalGroup(
            pestRegionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestRegionalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(pestRegionalLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pestRegionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pestRegionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pestRegionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pestRegionalLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(153, 153, 153)
                                .addComponent(correo2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pestRegionalLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(85, 85, 85)
                                .addComponent(fechaReg2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pestRegionalLayout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addGroup(pestRegionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dni_rep2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nombre_rep2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        pestRegionalLayout.setVerticalGroup(
            pestRegionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pestRegionalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pestRegionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(nombre_rep2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pestRegionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestRegionalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12))
                    .addGroup(pestRegionalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dni_rep2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pestRegionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(correo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pestRegionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(fechaReg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Regional", pestRegional);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Distrito", "Estado Activo", "Cant. Adhs Faltantes", "Validar Nuevos", "Eliminar"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel13.setText("Nombre del Representante:");

        dni_rep3.setEditable(false);

        nombre_rep3.setEditable(false);

        jLabel14.setText("Dni del Representante:");

        jLabel6.setText("Fecha de Registro:");

        correo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correo3ActionPerformed(evt);
            }
        });

        jLabel19.setText("Correo:");

        javax.swing.GroupLayout pestDistritalLayout = new javax.swing.GroupLayout(pestDistrital);
        pestDistrital.setLayout(pestDistritalLayout);
        pestDistritalLayout.setHorizontalGroup(
            pestDistritalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestDistritalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pestDistritalLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pestDistritalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pestDistritalLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(nombre_rep3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pestDistritalLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dni_rep3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pestDistritalLayout.createSequentialGroup()
                        .addGroup(pestDistritalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pestDistritalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaReg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(correo3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pestDistritalLayout.setVerticalGroup(
            pestDistritalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pestDistritalLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pestDistritalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nombre_rep3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pestDistritalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(dni_rep3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pestDistritalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pestDistritalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechaReg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Distrital", pestDistrital);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Local", "Estado Activo", "Cant. Adhs Faltantes", "Validar Nuevos", "Eliminar"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jLabel15.setText("Nombre del Representante:");

        dni_rep4.setEditable(false);

        nombre_rep4.setEditable(false);

        jLabel16.setText("Dni del Representante:");

        jLabel20.setText("Fecha de Registro:");

        correo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correo4ActionPerformed(evt);
            }
        });

        jLabel21.setText("Correo:");

        javax.swing.GroupLayout pestLocalLayout = new javax.swing.GroupLayout(pestLocal);
        pestLocal.setLayout(pestLocalLayout);
        pestLocalLayout.setHorizontalGroup(
            pestLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestLocalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pestLocalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pestLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestLocalLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(153, 153, 153)
                        .addComponent(correo4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pestLocalLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(99, 99, 99)
                        .addComponent(fechaReg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pestLocalLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(pestLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dni_rep4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_rep4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pestLocalLayout.setVerticalGroup(
            pestLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pestLocalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pestLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(nombre_rep4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pestLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(dni_rep4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(pestLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(correo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pestLocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(fechaReg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Local", pestLocal);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Institucional", "Estado Activo", "Cant. Adhs Faltantes", "Validar Nuevos", "Eliminar"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jLabel17.setText("Nombre del Representante:");

        dni_rep5.setEditable(false);

        nombre_rep5.setEditable(false);

        jLabel18.setText("Dni del Representante:");

        jLabel22.setText("Fecha de Registro:");

        correo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correo5ActionPerformed(evt);
            }
        });

        jLabel23.setText("Correo:");

        javax.swing.GroupLayout pestInstitucionLayout = new javax.swing.GroupLayout(pestInstitucion);
        pestInstitucion.setLayout(pestInstitucionLayout);
        pestInstitucionLayout.setHorizontalGroup(
            pestInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestInstitucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pestInstitucionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pestInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestInstitucionLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(153, 153, 153)
                        .addComponent(correo5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pestInstitucionLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(99, 99, 99)
                        .addComponent(fechaReg5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pestInstitucionLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(pestInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dni_rep5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre_rep5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pestInstitucionLayout.setVerticalGroup(
            pestInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestInstitucionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pestInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(nombre_rep5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pestInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(dni_rep5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pestInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(correo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pestInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(fechaReg5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        jTabbedPane3.addTab("Institucional", pestInstitucion);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel4.setText("Nombre del Partido");

        adherentesRevision.setText("Adherentes en Revision");
        adherentesRevision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adherentesRevisionActionPerformed(evt);
            }
        });

        nombre_partido.setEditable(false);
        nombre_partido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_partidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre_partido, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adherentesRevision)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_partido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adherentesRevision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void validarNuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarNuevosActionPerformed
        //jTabbedPane3.setVisible(false);
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            //            System.out.println(selectedFile.getName());
        }
        try{
            //            System.out.println("hola");
            Thread.sleep(2000);
            jTabbedPane3.setVisible(true);
            Terminado2 dialog = new Terminado2(new javax.swing.JFrame(), true);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);

            //            System.out.println("hola");
        }catch(Exception e){

        }
        //        jTabbedPane3.setVisible(true);
        //        imP5.setVisible(false);
    }//GEN-LAST:event_validarNuevosActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int n =JOptionPane.showConfirmDialog (null, "Estas Seguro que deseas eliminar?","Advertencia",dialogButton);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void adherentesRevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adherentesRevisionActionPerformed
        /*
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel11.setVisible(false);
        panelRegistroPartidos.setVisible(false);
        jPanel18.setVisible(true);
*/
        padre.mostrarAdherentes(partidoPolitico);
    }//GEN-LAST:event_adherentesRevisionActionPerformed

    private void nombre_partidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_partidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_partidoActionPerformed

    private void correo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correo1ActionPerformed

    private void correo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correo2ActionPerformed

    private void correo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correo3ActionPerformed

    private void correo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correo4ActionPerformed

    private void correo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correo5ActionPerformed
    public void showDetail(PartidoPolitico p){
        nombre_partido.setText(p.getNombre());
        //nombre_rep.setText(p.getNombreRepresentante()+" "+p.getApellidoRepresentante());
        //dni_rep.setText(p.getDniRepresentante());
        partidoPolitico = p;
        ArrayList<PartidoPolitico> partidos = Manager.queryPartidoByName(p.getNombre());
        int[] tipos = Manager.queryTipoProcesoNombrePartido(p.getNombre());
        if(tipos[1]==0){
            jTabbedPane3.remove(pestNacional);
        } else{
            partidos = Manager.queryPartidoByNombTipo(p.getNombre(), 1);
            nombre_rep1.setText(partidos.get(0).getNombreRepresentante()+" "+partidos.get(0).getApellidoRepresentante());
            dni_rep1.setText(partidos.get(0).getDniRepresentante());
            correo1.setText(partidos.get(0).getCorreoPartido());
            fechaReg1.setCalendar(partidos.get(0).getFechaRegistro());
        }
        if(tipos[2]==0){            
            jTabbedPane3.remove(pestRegional);
        } else {
            partidos = Manager.queryPartidoByNombTipo(p.getNombre(), 2);
            nombre_rep2.setText(partidos.get(0).getNombreRepresentante()+" "+partidos.get(0).getApellidoRepresentante());
            dni_rep2.setText(partidos.get(0).getDniRepresentante());
            correo2.setText(partidos.get(0).getCorreoPartido());
            fechaReg2.setCalendar(partidos.get(0).getFechaRegistro());
            regionesModel = new RegionModel();
            ArrayList<String> regs = new ArrayList<String>();
            regionesModel.partidos = partidos;
            for(int i =0;i<partidos.size();i++){
                Region reg = Manager.queryByIdRegion(partidos.get(i).getIdRegion());
                regs.add(reg.getNombre());
            }
            regionesModel.regiones = regs;
            tabla_region.setModel(regionesModel);
            TableCellRenderer buttonRenderer = new JTableButtonRenderer();
            tabla_region.getColumnModel().getColumn(3).setCellRenderer(buttonRenderer);
            tabla_region.getColumnModel().getColumn(4).setCellRenderer(buttonRenderer);
            //regionesModel.fireTableChanged(null);
        
        }
        if(tipos[3]==0){
            jTabbedPane3.remove(pestDistrital);
        }
        if(tipos[4]==0){
            jTabbedPane3.remove(pestLocal);
        }
        if(tipos[5]==0){
            jTabbedPane3.remove(pestInstitucion);
        }
         jTabbedPane3.repaint();
    }
    
    private static class JTableButtonRenderer implements TableCellRenderer {        
        @Override 
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            JButton button = (JButton)value;
            return button;  
        }
    }
    
    public class RegionModel extends AbstractTableModel{
	ArrayList<String> regiones = null;	
        ArrayList<PartidoPolitico> partidos = null; 
	String [] titles = {"Region","Estado","Cant Adhs Falt", "Validar nuevos", "Eliminar"};
        Class<?>[] COLUMN_TYPES = new Class<?>[] {String.class, String.class, String.class, JButton.class,  JButton.class};
		
        @Override
		public int getColumnCount() {
			// TODO Auto-generated method stub
			return titles.length;
		}

		@Override
		public int getRowCount() {
			// TODO Auto-generated method stub
			return partidos.size();
		}

		@Override
		public Object getValueAt(int row, int col) {
                    String value = "";
                    switch(col){
			case 0:  value = regiones.get(row); break;
			case 1:  value = partidos.get(row).getEstado(); break;
			case 2:  value = "" + partidos.get(row).getCantidadRegistrosValidos(); break;
                        case 3: final JButton button = new JButton("check");
                                button.addActionListener(new ActionListener() {
                                    public void actionPerformed(ActionEvent arg0) {
                                        JOptionPane.showMessageDialog(JOptionPane.getFrameForComponent(button), 
                                                "Button clicked for row "+row);
                                    }
                                });
                                return button; 
                        case 4: final JButton button1 = new JButton("X");
                                button1.addActionListener(new ActionListener() {
                                    public void actionPerformed(ActionEvent arg0) {
                                        JOptionPane.showMessageDialog(JOptionPane.getFrameForComponent(button1), 
                                                "Button clicked for row "+row);
                                    }
                                });
                                return button1;
			}
			return value;
		}
                
        @Override 
        public Class<?> getColumnClass(int columnIndex) {
            return COLUMN_TYPES[columnIndex];
        }
		
		public String getColumnName(int col){
			return titles[col];
		}
		
	}
    private RegionModel regionesModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adherentesRevision;
    private javax.swing.JTextField correo1;
    private javax.swing.JTextField correo2;
    private javax.swing.JTextField correo3;
    private javax.swing.JTextField correo4;
    private javax.swing.JTextField correo5;
    private javax.swing.JTextField dni_rep1;
    private javax.swing.JTextField dni_rep2;
    private javax.swing.JTextField dni_rep3;
    private javax.swing.JTextField dni_rep4;
    private javax.swing.JTextField dni_rep5;
    private javax.swing.JTextField estado1;
    private com.toedter.calendar.JDateChooser fechaReg1;
    private com.toedter.calendar.JDateChooser fechaReg2;
    private com.toedter.calendar.JDateChooser fechaReg3;
    private com.toedter.calendar.JDateChooser fechaReg4;
    private com.toedter.calendar.JDateChooser fechaReg5;
    private javax.swing.JButton jButton21;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField nombre_partido;
    private javax.swing.JTextField nombre_rep1;
    private javax.swing.JTextField nombre_rep2;
    private javax.swing.JTextField nombre_rep3;
    private javax.swing.JTextField nombre_rep4;
    private javax.swing.JTextField nombre_rep5;
    private javax.swing.JPanel pestDistrital;
    private javax.swing.JPanel pestInstitucion;
    private javax.swing.JPanel pestLocal;
    private javax.swing.JPanel pestNacional;
    private javax.swing.JPanel pestRegional;
    private javax.swing.JTable tabla_region;
    private javax.swing.JButton validarNuevos;
    // End of variables declaration//GEN-END:variables
}
