/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grupob;

import controlador.Manager;
import java.awt.ItemSelectable;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Distrito;
import model.Local;
import model.Region;

/**
 *
 * @author Franz
 */
public class RegistrarLocal extends javax.swing.JFrame {

    Local local = null;
    String message = new String();
    boolean error = false;
    
    
    
    /**
     * Creates new form RegistrarLocal
     */
    public RegistrarLocal() {
        initComponents();
        local = new Local();
        cargarDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegNombreLocal = new javax.swing.JLabel();
        lblRegVotantesLocal = new javax.swing.JLabel();
        lblRegRegionLocal = new javax.swing.JLabel();
        lblRegDistritoLocal = new javax.swing.JLabel();
        txtRegNombreLocal = new javax.swing.JTextField();
        txtRegVotantesLocal = new javax.swing.JTextField();
        cbRegRegionLocal = new javax.swing.JComboBox();
        cbRegDistritoLocal = new javax.swing.JComboBox();
        lblTituloRegLocal = new javax.swing.JLabel();
        btnRegRegistrarLocal = new javax.swing.JButton();
        btnRegCancelarLocal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRegNombreLocal.setText("Nombre: ");

        lblRegVotantesLocal.setText("Cantidad de Votantes:");

        lblRegRegionLocal.setText("Region:");

        lblRegDistritoLocal.setText("Distrito:");

        cbRegRegionLocal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccion Region" }));

        cbRegDistritoLocal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Distrito" }));

        lblTituloRegLocal.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblTituloRegLocal.setText("REGISTRO DE LOCAL");

        btnRegRegistrarLocal.setText("Registrar");
        btnRegRegistrarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegRegistrarLocalActionPerformed(evt);
            }
        });

        btnRegCancelarLocal.setText("Cancelar");
        btnRegCancelarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegCancelarLocalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRegNombreLocal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRegNombreLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblRegVotantesLocal)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtRegVotantesLocal))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblRegDistritoLocal)
                                        .addComponent(lblRegRegionLocal))
                                    .addGap(39, 39, 39)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbRegRegionLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbRegDistritoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblTituloRegLocal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnRegRegistrarLocal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegCancelarLocal)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblTituloRegLocal)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegNombreLocal)
                    .addComponent(txtRegNombreLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegVotantesLocal)
                    .addComponent(txtRegVotantesLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegRegionLocal)
                    .addComponent(cbRegRegionLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegDistritoLocal)
                    .addComponent(cbRegDistritoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegRegistrarLocal)
                    .addComponent(btnRegCancelarLocal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegCancelarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegCancelarLocalActionPerformed
     
        this.dispose();
        
        
        
    }//GEN-LAST:event_btnRegCancelarLocalActionPerformed

    private void btnRegRegistrarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegRegistrarLocalActionPerformed

              String nombre = txtRegNombreLocal.getText();
        String cant  = txtRegVotantesLocal.getText();
        
        nombre = nombre.trim();
        cant = cant.trim();
        
        if(nombre.isEmpty()){
            error = true;
            message += "Nombre: Es invalido\n";
        }else
            local.setNombre(nombre);
        
        try{
        
            int votantes = Integer.parseInt(cant);
            if(votantes == 0){
                message += "Numero de votantes invalido\n";
                error = true;
            }else
                local.setCantidadVotantesRegistrados(votantes);
            
            
        }catch(Exception ex)
        {
        
           error = true;
           message += "Cantidad votantes no es numerico\n";
          
        
        };
        
        
        if(cbRegRegionLocal.getSelectedIndex() == 0){
        
            message += "No selecciona la region\n";
            error = true;
        }
        
        if (cbRegDistritoLocal.getSelectedIndex() == 0){
        
            message += "No se selecciono distrito\n";
            error = true;
        }else
            local.setIdDistrito(((Distrito)cbRegDistritoLocal.getSelectedItem()).getId());
        
        
        if(error){
             JOptionPane.showMessageDialog(null,message);
             message="";
             error=false;
             return;
        }else{
        
                Manager.addLocal(local);
                JOptionPane.showMessageDialog(null,"Guardado satisfactoriamente");
                this.dispose();
        
        }
        
        


// TODO add your handling code here:
    }//GEN-LAST:event_btnRegRegistrarLocalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarLocal().setVisible(true);
            }
        });
    }
    
    public void cargarDatos(){
    
        ArrayList<Region> listaRegiones = Manager.queryAllRegion();
        
        if(listaRegiones.isEmpty()){

            return;
        }
            
        for( Region r : listaRegiones){
             cbRegRegionLocal.addItem(r);
           
        }   
        
        
        ItemListener il =  new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {
         
                if(e.getStateChange() == ItemEvent.SELECTED){
                
               
                    if (cbRegRegionLocal.getSelectedIndex() == 0){
                    
                        cbRegDistritoLocal.removeAllItems();
                        cbRegDistritoLocal.addItem("Seleccione Distrito");
                        return;
                               
                    }
                    
                    ItemSelectable is = e.getItemSelectable();
                    
                    Region dist = (Region) is.getSelectedObjects()[0];
                    System.out.println(dist.getId());
                    System.out.println(dist.getCantidadVotantesRegistrados());
                    ArrayList<Distrito> listaDistritos =    Manager.queryAllDistritoByRegion(dist.getId());
                    
                
                   
                    
                    
                    if(listaDistritos.isEmpty());
                        //do something
                    
                        
                     for(Distrito d : listaDistritos){
                     
                         cbRegDistritoLocal.addItem(d);
                       

                     }

                
                }
            
            
            }
        };

        cbRegRegionLocal.addItemListener(il);
        
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegCancelarLocal;
    private javax.swing.JButton btnRegRegistrarLocal;
    private javax.swing.JComboBox cbRegDistritoLocal;
    private javax.swing.JComboBox cbRegRegionLocal;
    private javax.swing.JLabel lblRegDistritoLocal;
    private javax.swing.JLabel lblRegNombreLocal;
    private javax.swing.JLabel lblRegRegionLocal;
    private javax.swing.JLabel lblRegVotantesLocal;
    private javax.swing.JLabel lblTituloRegLocal;
    private javax.swing.JTextField txtRegNombreLocal;
    private javax.swing.JTextField txtRegVotantesLocal;
    // End of variables declaration//GEN-END:variables
}
